### ISSUE TITLE
:sparkles: Allow keys as tags

### ISSUE THREAD

**Issue by FH-Inway** [Wesztman/mkdocs-azure-pipelines#19]
Neat tool, found it easy to setup and use. Could use an example (some pipeline/template yaml files and the markdown files generated from them), maybe even hosted as a mkdocs site, so that people can get a quick first impression what the result would look like.

While playing around with it, I noticed that the currently supported tags for extra content is limited. I like the idea of the tags, reminds me of PowerShell's [comment based help](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_comment_based_help?view=powershell-7.5). It would be useful to have additional tags to add extra content to. First step could be the keys. E.g. support something like this:

``` yaml
#:::trigger-start:::
# Define the trigger that will cause this pipeline to run.
# The following trigger will fire if changes are committed to the
# develop branch, but not to one of the folder defined in exclude.
#:::trigger-end:::
trigger:
  batch: false # Batch changes while a build is in progress
  branches:
    include:
    - develop
  paths:
    exclude:
    - /.git*
    - /.azuredevops*
```
Which would result in the following markdown:

```markdown
##Triggers

Define the trigger that will cause this pipeline to run.
The following trigger will fire if changes are committed to the
develop branch, but not to one of the folder defined in exclude.`

    ```yaml
    trigger:
      batch: false # Batch changes while a build is in progress
      branches:
        include:
        - develop
      paths:
        exclude:
        - /.git*
        - /.azuredevops*
    ```
```

Next step could be custom tags with some configuration to e.g. specify header level.
